#!/bin/bash

## Deploy khodakhah/nodcms-bundle

# Setup variables
SOURCE=$1
TARGET=$2
RELEASE=$3

echo "Preparing for version $3"
echo "Merging files from $1 to $2"

# Prepare the source
cd ${SOURCE}
git checkout master
# Composer validate
composer validate --strict

# Install dependencies
composer install --prefer-dist --no-progress

# Prepare the target
cd ${TARGET}
git checkout master
rm -rf *

# Copy common files
releasable='nodcms-core nodcms-about nodcms-articles nodcms-blog nodcms-gallery nodcms-installer nodcms-layout nodcms-portfolio nodcms-pricingtable nodcms-services nodcms-user public writable LICENSE'
for fff in $releasable;
do
  cp -Rf ${SOURCE}/$fff ./
done

# Copy repo-specific files
cp -Rf ${SOURCE}/admin/bundle/. ./

DIR=${SOURCE}/vendor/codeigniter4/framework/system
if [ ! -d ${DIR} ]
then
  if [ ! -f ${DIR} ]
  then
    echo "Directory or file ${DIR} DOES NOT exists."
    exit 1
  fi
fi
# Copy system
cp -Rf ${DIR} ./

# Commit the changes
#git add .
#git commit -m "Release ${RELEASE}"
#git push
